const data={
    user1:{
        name:"Fake User_1",
        profileImg:"../public/assets/image/person1.jpg",
        job:"Web Development",
        description:"As a web development intern, I'll delve into coding languages like HTML, CSS, and JavaScript to create dynamic websites and applications. Collaborating with experienced developers, I'll learn to build user-friendly interfaces and gain practical experience with frameworks like React or Angular.",
        certificatesNumber: 5,
        certificateImg: "../public/assets/certificate/certificate1.jpg",
        projectsNumber: 6,
        commendationNumber: 3,
    },
    user2:{
        name:"Fake User_2",
        profileImg:"../public/assets/image/person2.jpg",
        job:"Cybersecurity Engineering",
        description:"In my cybersecurity internship, I'll work alongside professionals to implement security measures and analyze threats. Through hands-on experience with tools like penetration testing frameworks, I'll develop expertise in threat detection and incident response.",
        certificatesNumber: 3,
        certificateImg: "../public/assets/certificate/certificate2.jpg",
        projectsNumber: 5,
        commendationNumber: 4,
    },
    user3:{
        name:"Fake User_3",
        profileImg:"../public/assets/image/person3.jpg",
        job:"Software Engineering",
        description:"Joining a software engineering internship, I'll contribute to the development of software solutions using languages like Java or Python. Working in agile teams, I'll participate in the full development lifecycle, from design to deployment",
        certificatesNumber: 9,
        certificateImg: "../public/assets/certificate/certificate3.jpg",
        projectsNumber: 4,
        commendationNumber: 2,
    },
    user4:{
        name:"Fake User_4",
        profileImg:"../public/assets/image/person4.jpg",
        job:"Data Science",
        description:"As a data science intern, I'll leverage programming languages like Python or R to analyze data and build predictive models. Collaborating with data scientists, I'll gain practical experience in data-driven decision-making.",
        certificatesNumber: 5,
        certificateImg: "../public/assets/certificate/certificate4.jpg",
        projectsNumber: 3,
        commendationNumber: 1,
    },
    user5:{
        name:"Fake User_5",
        profileImg:"../public/assets/image/person5.jpg",
        job:"Marketing",
        description:"In a marketing internship, I'll assist with developing strategies, conducting research, and executing campaigns across various channels, gaining hands-on experience in brand promotion and customer engagement.",
        certificatesNumber: 1,
        certificateImg: "../public/assets/certificate/certificate5.jpg",
        projectsNumber: 5,
        commendationNumber: 3,
    },
    user6:{
        name:"Fake User_6",
        profileImg:"../public/assets/image/person6.jpg",
        job:"Mechanical Engineering",
        description:"In a mechanical engineering internship, I'll gain hands-on experience in designing and testing mechanical components. Working with engineers, I'll apply engineering principles to solve real-world problems in industries like automotive and aerospace.",
        certificatesNumber: 8,
        certificateImg: "../public/assets/certificate/certificate6.jpg",
        projectsNumber: 2,
        commendationNumber: 1,
    },
    user7:{
        name:"Fake User_7",
        profileImg:"../public/assets/image/person7.jpg",
        job:"Graphic Design",
        description:"As a graphic design intern, I'll create visual content and assets for branding and advertising, using software like Adobe Creative Suite to produce logos, illustrations, and other design elements.",
        certificatesNumber: 5,
        certificateImg: "../public/assets/certificate/certificate7.jpg",
        projectsNumber: 7,
        commendationNumber: 5,
    },
    user8:{
        name:"Fake User_8",
        profileImg:"../public/assets/image/person8.jpg",
        job:"Human Resources ",
        description:"In an HR internship, I'll support recruitment, employee relations, and talent management initiatives, learning about HR processes and practices aimed at attracting and developing talent within organizations.",
        certificatesNumber: 0,
        certificateImg: "../public/assets/certificate/certificate8.jpg",
        projectsNumber: 0,
        commendationNumber: 0,
    },
    user9:{
        name:"Fake User_9",
        profileImg:"../public/assets/image/person9.jpg",
        job:"Finance/Accounting",
        description:"As a finance/accounting intern, I'll assist with financial analysis, budgeting, and reporting activities, gaining exposure to corporate finance and accounting principles while contributing to financial decision-making processes.",
        certificatesNumber: 0,
        certificateImg: "../public/assets/certificate/certificate9.jpg",
        projectsNumber: 3,
        commendationNumber: 2,
    },
}

export default data;